apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - account-service.yaml
  - batch-processor.yaml
  - fraud-detection.yaml
  - frontend.yaml
  - gateway-api.yaml
  - notification-service.yaml
  - traffic-generator.yaml
  - transaction-service.yaml
