#!/usr/bin/env bash
# =============================================================================
# generate-eks-kustomization.sh
# Generates deploy/kubernetes/overlays/eks/kustomization.yaml from live
# Terraform output so ECR URLs always match the current AWS account/region.
#
# Called automatically by: make deploy-k8s-eks
# Requires: terraform apply (make tf-apply-aws) to have completed.
#
# NOTE: the frontend Service is intentionally left as `type: NodePort` here
# (same as local) — it is NOT patched to `type: LoadBalancer`. Exposure to
# the internet is handled entirely by a Terraform-managed NLB
# (aws_lb.frontend in deploy/terraform/aws/main.tf) that targets the fixed
# NodePorts (30080 HTTP, 30443 HTTPS) across the EKS managed node group's
# Auto Scaling Group.
#
# This used to work the other way around (Kubernetes provisioned a Classic
# ELB dynamically via `type: LoadBalancer`), but that ELB — and its
# auto-created security group — lived entirely outside Terraform state. If
# the EKS cluster was ever deleted before that Service was cleaned up, the
# controller that would release the ELB was gone, and it became a
# permanently orphaned resource blocking VPC/subnet deletion. Moving the
# load balancer into Terraform (as a first-class resource with the cluster
# as an implicit dependency) means `terraform destroy` always tears it down
# in the correct order — see deploy/terraform/aws/main.tf's "FRONTEND LOAD
# BALANCER" section for the full explanation.
# =============================================================================
set -euo pipefail

OUT="deploy/kubernetes/overlays/eks/kustomization.yaml"
TF_DIR="deploy/terraform/aws"

echo "==> Generating $OUT from Terraform output..."

# Read ECR URLs from Terraform once
ECR_JSON=$(cd "$TF_DIR" && terraform output -json ecr_registry_urls 2>/dev/null) || {
  echo "ERROR: terraform output ecr_registry_urls failed."
  echo "       Run 'make tf-apply-aws' before 'make deploy-k8s-eks'."
  exit 1
}

get_url() {
  echo "$ECR_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin)['$1'])"
}

GW=$(get_url "gateway-api")
AC=$(get_url "account-service")
TX=$(get_url "transaction-service")
FD=$(get_url "fraud-detection")
NS=$(get_url "notification-service")
BP=$(get_url "batch-processor")

# Read ACM certificate ARN / domain / NLB hostname (may be empty if not yet applied)
ACM_CERT_ARN=$(cd "$TF_DIR" && terraform output -raw acm_certificate_arn 2>/dev/null || echo "")
DOMAIN_NAME=$(cd "$TF_DIR" && terraform output -raw domain_name 2>/dev/null || echo "")
FRONTEND_URL=$(cd "$TF_DIR" && terraform output -raw frontend_url 2>/dev/null || echo "")

if [ -n "$ACM_CERT_ARN" ]; then
  echo "    ACM certificate ARN: $ACM_CERT_ARN"
  echo "    NLB (Terraform-managed) serves HTTPS on :443 using this certificate"
else
  echo "    No ACM certificate — NLB (Terraform-managed) serves HTTP only on :80"
  echo "    Set domain_name in staging.tfvars and re-run make tf-apply-aws for HTTPS"
fi

ECR_REGISTRY=$(echo "$GW" | sed 's|/finance-app/gateway-api||')

cat > "$OUT" << HEREDOC
# =============================================================================
# Kustomize overlay — EKS
# =============================================================================
# AUTO-GENERATED by scripts/generate-eks-kustomization.sh — do not edit.
# Regenerated on every 'make deploy-k8s-eks' from live Terraform output.
# Gitignored: deploy/kubernetes/overlays/eks/kustomization.yaml
#
# ECR registry: ${ECR_REGISTRY}
# ACM cert:     ${ACM_CERT_ARN:-none}
# Domain:       ${DOMAIN_NAME:-<nlb-hostname>}
#
# NOTE: the frontend Service stays 'type: NodePort' here — public exposure
# is handled by the Terraform-managed NLB (aws_lb.frontend), not by
# Kubernetes' own LoadBalancer Service provisioning. See
# scripts/generate-eks-kustomization.sh for why.
# =============================================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/infrastructure
  - ../../base/services
  - storageclass.yaml

images:
  - name: finance-sample-app-gateway-api
    newName: ${GW}
    newTag: latest
  - name: finance-sample-app-account-service
    newName: ${AC}
    newTag: latest
  - name: finance-sample-app-transaction-service
    newName: ${TX}
    newTag: latest
  - name: finance-sample-app-fraud-detection
    newName: ${FD}
    newTag: latest
  - name: finance-sample-app-notification-service
    newName: ${NS}
    newTag: latest
  - name: finance-sample-app-batch-processor
    newName: ${BP}
    newTag: latest

patches:
  # imagePullPolicy: Always — EKS nodes have no local image cache.
  # Applied per-service; frontend (nginx) is excluded as it uses a public image.
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: gateway-api
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: account-service
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: transaction-service
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: fraud-detection
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: notification-service
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
    target:
      kind: Deployment
      name: batch-processor
HEREDOC

echo "    Written: $OUT"
echo "    ECR base: ${ECR_REGISTRY}"

# ── Update KEYCLOAK_PUBLIC_URL in the base ConfigMap ──────────────────────────────
# The NLB (aws_lb.frontend) is created by 'make tf-apply-aws', so its hostname
# is already known before the app is even deployed — no more "wait ~2 min for
# the Service to get an external IP" step like the old LoadBalancer Service
# required.
echo ""
if [ -n "$FRONTEND_URL" ]; then
  echo "NOTE: After 'kubectl apply -k deploy/kubernetes/overlays/eks', set"
  echo "      KEYCLOAK_PUBLIC_URL to the (already-known) NLB URL:"
  echo ""
  echo "  kubectl patch configmap app-config -n finance --type=merge \\"
  echo "    -p \"{\\\"data\\\":{\\\"KEYCLOAK_PUBLIC_URL\\\":\\\"${FRONTEND_URL}\\\"}}\""
  echo "  kubectl rollout restart deployment/keycloak deployment/frontend -n finance"
  echo ""
  if [ -n "$ACM_CERT_ARN" ]; then
    echo "  HTTPS is handled by the NLB using your ACM certificate."
    echo "  The nginx :8443 self-signed HTTPS listener is not needed for the main"
    echo "  domain on EKS, but stays available at:"
    echo "    $(cd "$TF_DIR" && terraform output -raw frontend_keycloak_https_url 2>/dev/null || echo '<see terraform output frontend_keycloak_https_url>')"
  else
    echo "  ⚠  No ACM certificate configured — dashboard is HTTP-only at ${FRONTEND_URL}."
    echo "  Set domain_name in staging.tfvars + make tf-apply-aws to enable HTTPS."
  fi
else
  echo "NOTE: frontend_url not yet available from Terraform output."
  echo "      Run 'make tf-apply-aws' first, then re-run this script."
fi
