apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - activemq.yaml
  - activemq-broker-config.yaml
  - keycloak.yaml
  - postgres.yaml
  - postgres-init.yaml
  - redis.yaml
